{{ $livro->titulo }}
{{ $livro->capa }}
{{ $livro->ano }}
{{ $livro->descricao }}
{{ $livro->preco }}
{{ $livro->download_previo }}
{{ $livro->download }}
{{ $livro->isbn }}
{{ $livro->categoria->categoria }}